//! Model limits lookup. Cascade: live models-cache (harvested from the
//! provider's `/v1/models`) → embedded models.dev snapshot
//! (`src/data/model_limits.json`, regenerated by the providers-sync skill)
//! → none. `/v1/models` stays authoritative when it carries the field.

use std::collections::HashMap;
use std::sync::LazyLock;

use serde::Deserialize;

use super::model_names::strip_context_suffix;
use super::models_cache::{ModelsCache, full_catalog_key};

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ModelLimits {
    pub context: Option<u64>,
    pub output: Option<u64>,
    pub tool_call: bool,
    pub reasoning: bool,
    pub attachment: bool,
    pub image_input: bool,
    /// False when the model rejects the `temperature` param (o-series,
    /// forced-reasoning claude variants).
    pub temperature: bool,
    pub deprecated: bool,
    /// Supported reasoning-effort values as published (may include levels
    /// like `xhigh`/`max` — consumers filter to what their tool accepts).
    pub reasoning_efforts: Vec<String>,
}

/// Cascade result: per-field merge of live cache over snapshot. `caps` are
/// snapshot-only (the cache doesn't store capability flags).
#[derive(Debug, Clone, Default)]
pub struct ResolvedLimits {
    pub context: Option<u64>,
    pub output: Option<u64>,
    pub caps: Option<&'static ModelLimits>,
}

#[derive(Deserialize)]
struct SnapshotFile {
    // BTreeMap: sorted iteration keeps fold-collision resolution deterministic.
    // Row: [context, output, flags, efforts] — see sync_model_limits.py.
    models: std::collections::BTreeMap<String, (Option<u64>, Option<u64>, String, String)>,
}

/// Keys folded (lowercase, `.`→`-`) so dot/dash version spellings match
/// (`claude-sonnet-4.6` ↔ `claude-sonnet-4-6`). Collisions keep the larger
/// context.
static SNAPSHOT: LazyLock<HashMap<String, ModelLimits>> = LazyLock::new(|| {
    let parsed: SnapshotFile = serde_json::from_str(include_str!("../data/model_limits.json"))
        .expect("embedded model_limits.json is valid");
    let mut map: HashMap<String, ModelLimits> = HashMap::with_capacity(parsed.models.len());
    for (id, (context, output, flags, efforts)) in parsed.models {
        let limits = ModelLimits {
            context,
            output,
            tool_call: flags.contains('t'),
            reasoning: flags.contains('r'),
            attachment: flags.contains('a'),
            image_input: flags.contains('i'),
            temperature: !flags.contains('f'),
            deprecated: flags.contains('d'),
            reasoning_efforts: efforts
                .split(',')
                .filter(|s| !s.is_empty())
                .map(str::to_string)
                .collect(),
        };
        let key = fold(&id);
        match map.get(&key) {
            Some(prev) if prev.context.unwrap_or(0) >= limits.context.unwrap_or(0) => {}
            _ => {
                map.insert(key, limits);
            }
        }
    }
    map
});

/// Folded keys sorted longest-first so the substring fallback picks the most
/// specific entry; keys < 6 chars excluded to avoid false hits (`o1`, `gpt-4`).
static KEYS_LONGEST_FIRST: LazyLock<Vec<&'static str>> = LazyLock::new(|| {
    let snapshot: &'static HashMap<String, ModelLimits> = &SNAPSHOT;
    let mut keys: Vec<&'static str> = snapshot
        .keys()
        .map(String::as_str)
        .filter(|k| k.len() >= 6)
        .collect();
    keys.sort_by(|a, b| b.len().cmp(&a.len()).then(a.cmp(b)));
    keys
});

fn fold(s: &str) -> String {
    s.trim().to_ascii_lowercase().replace('.', "-")
}

fn strip_date_suffix(s: &str) -> Option<&str> {
    let (base, suffix) = s.rsplit_once('-')?;
    (suffix.len() == 8 && suffix.chars().all(|c| c.is_ascii_digit())).then_some(base)
}

/// Snapshot-only lookup. Match order: exact (folded) → last `/`-segment →
/// `:variant` stripped (`:free`, bedrock `:0`) → `-YYYYMMDD` stripped →
/// longest-key substring (covers `us.anthropic.…` ids).
pub fn snapshot_limits(model: &str) -> Option<&'static ModelLimits> {
    let snapshot: &'static HashMap<String, ModelLimits> = &SNAPSHOT;
    let needle = fold(strip_context_suffix(model));
    if needle.is_empty() {
        return None;
    }
    if let Some(hit) = snapshot.get(&needle) {
        return Some(hit);
    }
    let segment = needle.rsplit('/').next().unwrap_or(&needle);
    if let Some(hit) = snapshot.get(segment) {
        return Some(hit);
    }
    let base = segment.split(':').next().unwrap_or(segment);
    if base != segment
        && let Some(hit) = snapshot.get(base)
    {
        return Some(hit);
    }
    if let Some(dateless) = strip_date_suffix(base)
        && let Some(hit) = snapshot.get(dateless)
    {
        return Some(hit);
    }
    KEYS_LONGEST_FIRST
        .iter()
        .find(|key| needle.contains(*key))
        .map(|key| &snapshot[*key])
}

/// True when the snapshot says `model` rejects the `temperature` parameter.
/// Unknown models return false — bridges only strip when confident.
pub fn rejects_temperature(model: &str) -> bool {
    snapshot_limits(model).is_some_and(|limits| !limits.temperature)
}

/// Capability sets for this process's local llama-server. Static because
/// `ResolvedLimits.caps` borrows `'static`; context comes from `SpawnInfo`.
static HF_LOCAL_CAPS_TEXT: LazyLock<ModelLimits> = LazyLock::new(|| hf_local_caps(false));
static HF_LOCAL_CAPS_VISION: LazyLock<ModelLimits> = LazyLock::new(|| hf_local_caps(true));

fn hf_local_caps(image_input: bool) -> ModelLimits {
    ModelLimits {
        context: None,
        output: None,
        tool_call: true,
        reasoning: false,
        attachment: false,
        image_input,
        temperature: true,
        deprecated: false,
        reasoning_efforts: Vec::new(),
    }
}

/// When `model` targets this process's local llama-server, advertise the
/// server's actual spawn parameters (context it was started with, whether
/// an mmproj is loaded) instead of snapshot guesses. One aivo process runs
/// at most one local server, so any hf-style ref maps to it.
fn hf_local_limits(base_url: Option<&str>, model: &str) -> Option<ResolvedLimits> {
    crate::services::huggingface::spawn_info()
        .and_then(|info| hf_local_limits_for(info, base_url, model))
}

fn hf_local_limits_for(
    info: &crate::services::huggingface::SpawnInfo,
    base_url: Option<&str>,
    model: &str,
) -> Option<ResolvedLimits> {
    let url_hit = base_url.is_some_and(|u| u.contains(&format!("127.0.0.1:{}", info.port)));
    let model_hit =
        model == info.model_name || crate::services::huggingface::is_hf_or_local_gguf(model);
    if !url_hit && !model_hit {
        return None;
    }
    let caps: &'static ModelLimits = if info.image_input {
        &HF_LOCAL_CAPS_VISION
    } else {
        &HF_LOCAL_CAPS_TEXT
    };
    Some(ResolvedLimits {
        context: Some(info.context),
        output: None,
        caps: Some(caps),
    })
}

/// THE canonical limits cascade. Every consumer (claude `[1m]` auto-tag,
/// codex catalog, loopback `/v1/models`) goes through here.
pub async fn resolve_limits(
    cache: &ModelsCache,
    base_url: Option<&str>,
    model: &str,
) -> ResolvedLimits {
    let stripped = strip_context_suffix(model);
    if let Some(local) = hf_local_limits(base_url, stripped) {
        return local;
    }
    let live = match base_url {
        Some(url) => match cache.get_metadata(&full_catalog_key(url), stripped).await {
            Some(meta) => Some(meta),
            None => cache.get_metadata(url, stripped).await,
        },
        None => None,
    };
    let snap = snapshot_limits(stripped);
    ResolvedLimits {
        context: live
            .as_ref()
            .and_then(|m| m.context_window)
            .or_else(|| snap.and_then(|s| s.context)),
        output: live
            .as_ref()
            .and_then(|m| m.max_output_tokens)
            .or_else(|| snap.and_then(|s| s.output)),
        caps: snap,
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::services::models_cache::ModelMetadata;
    use tempfile::TempDir;

    #[test]
    fn snapshot_parses_and_is_nontrivial() {
        // Catches a truncated or mangled regeneration of the embedded file.
        assert!(SNAPSHOT.len() >= 1000, "only {} entries", SNAPSHOT.len());
    }

    #[test]
    fn claude_sonnet_4_6_resolves_to_1m() {
        let hit = snapshot_limits("claude-sonnet-4-6").unwrap();
        assert_eq!(hit.context, Some(1_000_000));
        assert_eq!(hit.output, Some(64_000));
        assert!(hit.tool_call && hit.reasoning && hit.image_input);
    }

    #[test]
    fn claude_opus_4_7_resolves_to_1m() {
        assert_eq!(
            snapshot_limits("claude-opus-4-7").unwrap().context,
            Some(1_000_000)
        );
    }

    #[test]
    fn provider_prefixed_model_still_matches() {
        for id in [
            "anthropic/claude-opus-4-7",
            "us.anthropic.claude-sonnet-4-6",
            "openrouter/anthropic/claude-sonnet-4.6",
        ] {
            assert_eq!(
                snapshot_limits(id).unwrap().context,
                Some(1_000_000),
                "{id}"
            );
        }
    }

    #[test]
    fn dot_and_dash_version_spellings_match() {
        assert_eq!(
            snapshot_limits("claude-sonnet-4.6").unwrap().context,
            Some(1_000_000)
        );
    }

    #[test]
    fn date_suffixed_id_matches_base() {
        assert_eq!(
            snapshot_limits("claude-sonnet-4-5-20250929")
                .unwrap()
                .context,
            Some(1_000_000)
        );
    }

    #[test]
    fn context_suffix_is_stripped() {
        assert_eq!(
            snapshot_limits("claude-sonnet-4-6[1m]").unwrap().context,
            Some(1_000_000)
        );
    }

    #[test]
    fn case_insensitive_match() {
        assert_eq!(
            snapshot_limits("Claude-Sonnet-4-6").unwrap().context,
            Some(1_000_000)
        );
    }

    #[test]
    fn grok_4_3_resolves_to_1m() {
        assert_eq!(
            snapshot_limits("grok-4.3").unwrap().context,
            Some(1_000_000)
        );
        assert_eq!(
            snapshot_limits("xai/grok-4.3").unwrap().context,
            Some(1_000_000)
        );
    }

    #[test]
    fn grok_4_fast_resolves_to_2m() {
        for id in ["grok-4-fast", "x-ai/grok-4-fast", "grok-4-fast-reasoning"] {
            assert_eq!(
                snapshot_limits(id).unwrap().context,
                Some(2_000_000),
                "{id}"
            );
        }
    }

    #[test]
    fn gpt_4_1_family_resolves_to_1m_class() {
        assert_eq!(snapshot_limits("gpt-4.1").unwrap().context, Some(1_047_576));
        assert_eq!(
            snapshot_limits("openai/gpt-4.1-mini").unwrap().context,
            Some(1_047_576)
        );
    }

    #[test]
    fn short_context_models_resolve_below_1m() {
        // The old static table returned None for these; the snapshot knows
        // their real (sub-1M) limits.
        assert_eq!(
            snapshot_limits("gpt-3.5-turbo").unwrap().context,
            Some(16_385)
        );
        assert_eq!(
            snapshot_limits("claude-3-haiku").unwrap().context,
            Some(200_000)
        );
    }

    #[test]
    fn variant_only_listings_resolve_for_plain_id() {
        // poolside/laguna-m.1 is mostly listed as `…:free`; the generator
        // merges variants into the base id (131,040 = poolside's own figure).
        assert_eq!(
            snapshot_limits("poolside/laguna-m.1").unwrap().context,
            Some(131_040)
        );
        // Explicit `:free` needles resolve too (colon-strip step).
        assert_eq!(
            snapshot_limits("openrouter/poolside/laguna-m.1:free")
                .unwrap()
                .context,
            Some(131_040)
        );
    }

    #[test]
    fn temperature_and_deprecated_flags_parse() {
        // o-series and forced-reasoning claude variants reject temperature.
        assert!(rejects_temperature("o3"));
        assert!(rejects_temperature("openai/gpt-5.4"));
        assert!(rejects_temperature("claude-opus-4-7"));
        // Normal models keep it; unknown models are never stripped.
        assert!(!rejects_temperature("claude-sonnet-4-6"));
        assert!(!rejects_temperature("deepseek-chat"));
        assert!(!rejects_temperature("totally-unknown-model-xyz"));
        // Some model in the snapshot carries the deprecated flag.
        assert!(SNAPSHOT.values().any(|l| l.deprecated));
    }

    #[test]
    fn reasoning_efforts_parse() {
        let efforts = &snapshot_limits("o3").unwrap().reasoning_efforts;
        assert!(efforts.iter().any(|e| e == "medium"), "{efforts:?}");
        assert!(
            snapshot_limits("deepseek-chat")
                .unwrap()
                .reasoning_efforts
                .is_empty()
        );
    }

    #[test]
    fn unknown_models_return_none() {
        assert_eq!(snapshot_limits("totally-unknown-model-xyz"), None);
        assert_eq!(snapshot_limits(""), None);
    }

    #[tokio::test]
    async fn cascade_prefers_live_cache_over_snapshot() {
        let dir = TempDir::new().unwrap();
        let cache = ModelsCache::with_path(dir.path().join("models-cache.json"));
        let mut metadata = std::collections::HashMap::new();
        metadata.insert(
            "claude-sonnet-4-6".to_string(),
            ModelMetadata {
                context_window: Some(200_000),
                ..Default::default()
            },
        );
        cache
            .set_with_metadata(
                &full_catalog_key("https://api.example.com"),
                vec!["claude-sonnet-4-6".to_string()],
                metadata,
            )
            .await;
        let resolved =
            resolve_limits(&cache, Some("https://api.example.com"), "claude-sonnet-4-6").await;
        assert_eq!(resolved.context, Some(200_000));
        // Cache has no output → snapshot fills the gap (per-field merge).
        assert_eq!(resolved.output, Some(64_000));
        assert!(resolved.caps.unwrap().tool_call);
    }

    #[tokio::test]
    async fn cascade_falls_back_to_snapshot_on_cold_cache() {
        let dir = TempDir::new().unwrap();
        let cache = ModelsCache::with_path(dir.path().join("models-cache.json"));
        let resolved =
            resolve_limits(&cache, Some("https://api.example.com"), "claude-sonnet-4-6").await;
        assert_eq!(resolved.context, Some(1_000_000));
        assert_eq!(resolved.output, Some(64_000));
    }

    #[test]
    fn hf_local_override_matches_loopback_url_name_and_refs() {
        let info = crate::services::huggingface::SpawnInfo {
            port: 18080,
            context: 40_960,
            image_input: true,
            model_name: "Qwen2.5-0.5B-Instruct-GGUF".to_string(),
        };
        // Loopback base URL.
        let by_url = hf_local_limits_for(&info, Some("http://127.0.0.1:18080/v1"), "anything")
            .expect("url match");
        assert_eq!(by_url.context, Some(40_960));
        assert!(by_url.caps.unwrap().image_input);
        assert!(by_url.caps.unwrap().tool_call);
        // Display model name.
        assert!(hf_local_limits_for(&info, None, "Qwen2.5-0.5B-Instruct-GGUF").is_some());
        // hf-style refs map to the (only) local server.
        assert!(hf_local_limits_for(&info, None, "hf:Qwen/Qwen2.5-0.5B-Instruct-GGUF").is_some());
        // Unrelated remote model on an unrelated URL: untouched.
        assert!(
            hf_local_limits_for(&info, Some("https://api.example.com"), "claude-sonnet-4-6")
                .is_none()
        );
    }

    #[test]
    fn hf_local_override_text_only_without_mmproj() {
        let info = crate::services::huggingface::SpawnInfo {
            port: 18081,
            context: 32_768,
            image_input: false,
            model_name: "m".to_string(),
        };
        let limits = hf_local_limits_for(&info, Some("http://127.0.0.1:18081/v1"), "m").unwrap();
        assert!(!limits.caps.unwrap().image_input);
        assert_eq!(limits.output, None);
    }

    #[tokio::test]
    async fn cascade_unknown_everywhere_is_empty() {
        let dir = TempDir::new().unwrap();
        let cache = ModelsCache::with_path(dir.path().join("models-cache.json"));
        let resolved = resolve_limits(&cache, None, "totally-unknown-model-xyz").await;
        assert_eq!(resolved.context, None);
        assert_eq!(resolved.output, None);
        assert!(resolved.caps.is_none());
    }
}
